### ISSUE TITLE
无法退出登录

### ISSUE THREAD

**Issue by Alex0314H** [un-pany/v3-electron-vite#3]
报错：runtime-core.esm-bundler.js:218 Uncaught TypeError: sessionStorage.remove is not a function

sessionStorage.remove is not a function
    at removeToken (sessionStorage.ts:13:18)
    at Proxy.logout (user.ts:65:5)
    at Proxy.<anonymous> (pinia.mjs:1359:30)
    at logout (index.vue:32:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:711:9)
    at runtime-core.esm-bundler.js:7372:53
    at dropdown-item.vue:91:11
    at handleEvent (event.ts:3:60)

**Comment by pany-ang** [comment]
remove 修改为 removeItem

**Comment by nevlf** [comment]
已修复
